# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "ecomshaper-sales-pop"
client_id = "52330548a781c6db5f19327bf9349410"
application_url = "https://must-newest-cook-spending.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://must-newest-cook-spending.trycloudflare.com/auth/callback",
  "https://must-newest-cook-spending.trycloudflare.com/auth/shopify/callback",
  "https://must-newest-cook-spending.trycloudflare.com/api/auth/callback",
  "https://must-newest-cook-spending.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "sales-pop-v4.myshopify.com"
